import '../../models/lesson.dart';
import '../../models/quiz.dart';

final csharpLesson41 = Lesson(
  language: 'C#',
  title: 'Anonymous Types and Dynamic',
  content: """
🎯 METAPHOR:
An anonymous type is like a sticky note with data on it.
You write "Name: Alice, Score: 95" on it — just for right
now, for this one task. You don't need a whole filing
cabinet system (a named class) for a quick note. It is
immutable, typed, and thrown away when done.

dynamic is like a package labeled "OPEN AT RUNTIME."
The compiler doesn't check what's inside. You trust that
when you open it, what you need will be there. This is
the opposite of C#'s usual type safety — it defers ALL
type checking to runtime. Powerful for interop with
dynamic languages (Python, JavaScript, COM objects),
dangerous everywhere else.

📖 EXPLANATION:
ANONYMOUS TYPES:
  → Created with new { Property = value, ... }
  → Type is generated by the compiler, has no name
  → Properties are read-only (immutable)
  → Equality is value-based (same property values = equal)
  → Primarily used in LINQ projections
  → Cannot be returned from methods (use records/tuples)

DYNAMIC:
  → Bypasses compile-time type checking
  → All member access resolved at runtime via DLR
    (Dynamic Language Runtime)
  → Useful for: COM interop, JSON dynamic access,
    Python/IronPython interop, late-binding scenarios
  → Any invalid member access = RuntimeBinderException

─────────────────────────────────────
ANONYMOUS TYPE vs TUPLE vs RECORD:
─────────────────────────────────────
  Anonymous  new { Name = "x" }   immutable, LINQ-only, no return
  Tuple      (string Name, int)   returnable, lightweight, mutable
  Record     record P(string N)   returnable, immutable, full type

  Use anonymous for LINQ projections only.
  Use records or tuples when you need to return data.

💻 CODE:
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    static void Main()
    {
        // ─── ANONYMOUS TYPES ──────────────────────────────
        var person = new { Name = "Alice", Age = 30, IsAdmin = true };

        Console.WriteLine(person.Name);     // Alice
        Console.WriteLine(person.Age);      // 30
        // person.Name = "Bob";  // ERROR: properties are read-only!

        // Type is anonymous but strongly typed:
        Console.WriteLine(person.GetType().Name);
        // <>f__AnonymousType0`3

        // Value-based equality:
        var p1 = new { X = 1, Y = 2 };
        var p2 = new { X = 1, Y = 2 };
        Console.WriteLine(p1.Equals(p2));  // True!

        // ─── ANONYMOUS TYPES IN LINQ (primary use) ────────
        var students = new[]
        {
            new { Name = "Alice",   GPA = 3.8, Major = "CS" },
            new { Name = "Bob",     GPA = 3.2, Major = "Math" },
            new { Name = "Charlie", GPA = 3.9, Major = "CS" },
        };

        var summary = students
            .Where(s => s.GPA >= 3.5)
            .Select(s => new
            {
                s.Name,
                s.GPA,
                Label = s.GPA > 3.8 ? "Honors" : "Good"
            })
            .OrderByDescending(s => s.GPA);

        foreach (var s in summary)
            Console.WriteLine(\$"{s.Name}: {s.GPA} ({s.Label})");
        // Charlie: 3.9 (Honors)
        // Alice:   3.8 (Good)

        // ─── DYNAMIC ──────────────────────────────────────
        dynamic d = 42;
        Console.WriteLine(d);           // 42
        Console.WriteLine(d.GetType()); // System.Int32

        d = "hello";                    // can change type!
        Console.WriteLine(d.ToUpper()); // HELLO — resolved at runtime

        d = new List<int> { 1, 2, 3 };
        Console.WriteLine(d.Count);     // 3

        // ─── DYNAMIC WITH ANONYMOUS OBJECTS ───────────────
        dynamic config = new
        {
            Host  = "localhost",
            Port  = 5432,
            Debug = true
        };
        Console.WriteLine(config.Host);  // localhost
        // config.Missing;  // RuntimeBinderException at runtime!

        // ─── EXPANDOOBJECT — truly dynamic object ──────────
        dynamic expando = new System.Dynamic.ExpandoObject();
        expando.Name  = "Alice";
        expando.Age   = 30;
        expando.Greet = (Action)(() =>
            Console.WriteLine(\$"Hello, {expando.Name}!"));

        Console.WriteLine(expando.Name);  // Alice
        expando.Greet();                  // Hello, Alice!

        // Cast to IDictionary to inspect keys:
        var dict = (IDictionary<string, object>)expando;
        foreach (var kvp in dict)
            Console.WriteLine(\$"  {kvp.Key}: {kvp.Value}");

        // ─── DYNAMIC DUCK TYPING ──────────────────────────
        // Calls Speak() on ANY object that has it — no interface needed
        static void MakeNoise(dynamic animal) => animal.Speak();

        MakeNoise(new Dog());  // Woof!
        MakeNoise(new Cat());  // Meow!

        // ─── WHEN TO USE DYNAMIC ──────────────────────────
        Console.WriteLine();
        Console.WriteLine("Dynamic use cases:");
        Console.WriteLine("  COM automation (Excel, Word)");
        Console.WriteLine("  IronPython / IronRuby interop");
        Console.WriteLine("  Legacy reflection-heavy code");
        Console.WriteLine("  ExpandoObject scripting APIs");
        Console.WriteLine("  NOT for general application code!");
    }
}

class Dog { public void Speak() => Console.WriteLine("Woof!"); }
class Cat { public void Speak() => Console.WriteLine("Meow!"); }

📝 KEY POINTS:
✅ Anonymous types are perfect for LINQ Select projections
✅ Anonymous type properties are immutable (get-only)
✅ Two anonymous types with same property names/types/order are value-equal
✅ ExpandoObject lets you add properties dynamically at runtime
✅ dynamic is essential for COM automation and Python interop
❌ Don't return anonymous types from methods — use records/tuples instead
❌ dynamic has no IntelliSense — all errors appear at runtime only
❌ Avoid dynamic in performance-critical code — DLR dispatch is slow
❌ Mixing dynamic with generics can cause subtle runtime failures
""",
  quiz: [
    Quiz(question: 'What is the primary use case for anonymous types in C#?', options: [
      QuizOption(text: 'LINQ Select projections — shaping query results without defining a named class', correct: true),
      QuizOption(text: 'Returning multiple values from methods', correct: false),
      QuizOption(text: 'Replacing records for all immutable data', correct: false),
      QuizOption(text: 'Creating objects that can change their properties at runtime', correct: false),
    ]),
    Quiz(question: 'What happens when you access a non-existent member on a dynamic variable?', options: [
      QuizOption(text: 'A RuntimeBinderException is thrown at runtime', correct: true),
      QuizOption(text: 'A compile-time error is generated', correct: false),
      QuizOption(text: 'null is returned safely', correct: false),
      QuizOption(text: 'The member is created automatically', correct: false),
    ]),
    Quiz(question: 'What does ExpandoObject allow that a regular anonymous type does not?', options: [
      QuizOption(text: 'Adding and removing properties dynamically at runtime', correct: true),
      QuizOption(text: 'Value-based equality comparison', correct: false),
      QuizOption(text: 'Returning the object from a method with a named type', correct: false),
      QuizOption(text: 'Immutable read-only properties', correct: false),
    ]),
  ],
);